import { defaultParameters } from './constants';
import type { CostItem, RevenueItem, Scenario } from './types';

const id = (prefix: string) => `${prefix}_${crypto.randomUUID()}`;

const today = () => new Date().toISOString().slice(0, 10);

const now = () => new Date().toISOString();

const sampleRevenues = (): RevenueItem[] => [
  {
    id: id('rev'),
    name: 'BIM建模服务费用',
    calculationMode: 'manual',
    unitPrice: 0,
    quantity: 0,
    amountWithTax: 250000,
    taxRate: 0.06,
    rateKey: 'outputVatRate',
    note: '',
  },
];

const sampleCosts = (): CostItem[] => [
  {
    id: id('cost'),
    category: 'product_allocation',
    name: '产品分摊成本',
    calculationMode: 'manual',
    unitPrice: 0,
    quantity: 0,
    personDays: 0,
    rate: 0,
    rateKey: 'outsourcingVatRate',
    amountWithTax: 0,
    taxRate: 0,
    sourceNote: '',
    sortOrder: 1,
  },
  {
    id: id('cost'),
    category: 'infrastructure',
    name: '基础设施成本',
    calculationMode: 'manual',
    unitPrice: 0,
    quantity: 0,
    personDays: 0,
    rate: 0,
    rateKey: 'outsourcingVatRate',
    amountWithTax: 0,
    taxRate: 0.06,
    sourceNote: '',
    sortOrder: 2,
  },
  {
    id: id('cost'),
    category: 'delivery_implementation',
    name: '框架外包',
    calculationMode: 'unit_quantity',
    unitPrice: 163600,
    quantity: 1,
    personDays: 0,
    rate: 0,
    rateKey: 'outsourcingVatRate',
    amountWithTax: 0,
    taxRate: 0.06,
    sourceNote: '税率1.06，外采成本，BIM建模部分',
    sortOrder: 3,
  },
  {
    id: id('cost'),
    category: 'delivery_implementation',
    name: '自有人工',
    calculationMode: 'unit_quantity',
    unitPrice: 3100,
    quantity: 10,
    personDays: 0,
    rate: 0,
    rateKey: 'internalLaborTaxRate',
    amountWithTax: 0,
    taxRate: 0,
    sourceNote: '算量平台改造、清单核对等项目工作量估算',
    sortOrder: 4,
  },
  {
    id: id('cost'),
    category: 'delivery_implementation',
    name: '委外',
    calculationMode: 'manual',
    unitPrice: 0,
    quantity: 0,
    personDays: 0,
    rate: 0,
    rateKey: 'outsourcingVatRate',
    amountWithTax: 0,
    taxRate: 0.06,
    sourceNote: '',
    sortOrder: 5,
  },
  {
    id: id('cost'),
    category: 'custom_development',
    name: '框架外包',
    calculationMode: 'unit_quantity',
    unitPrice: 0,
    quantity: 0,
    personDays: 0,
    rate: 0,
    rateKey: 'outsourcingVatRate',
    amountWithTax: 0,
    taxRate: 0.06,
    sourceNote: '',
    sortOrder: 6,
  },
  {
    id: id('cost'),
    category: 'custom_development',
    name: '自有人工',
    calculationMode: 'unit_quantity',
    unitPrice: 3100,
    quantity: 0,
    personDays: 0,
    rate: 0,
    rateKey: 'internalLaborTaxRate',
    amountWithTax: 0,
    taxRate: 0,
    sourceNote: '',
    sortOrder: 7,
  },
  {
    id: id('cost'),
    category: 'custom_development',
    name: '委外',
    calculationMode: 'manual',
    unitPrice: 0,
    quantity: 0,
    personDays: 0,
    rate: 0,
    rateKey: 'outsourcingVatRate',
    amountWithTax: 0,
    taxRate: 0.06,
    sourceNote: '外采成本，税率1.06',
    sortOrder: 8,
  },
  {
    id: id('cost'),
    category: 'operation_maintenance',
    name: '运维合同',
    calculationMode: 'manual',
    unitPrice: 0,
    quantity: 0,
    personDays: 0,
    rate: 0,
    rateKey: 'outsourcingVatRate',
    amountWithTax: 0,
    taxRate: 0.06,
    sourceNote: '',
    sortOrder: 9,
  },
  {
    id: id('cost'),
    category: 'operation_maintenance',
    name: '自有人工',
    calculationMode: 'unit_quantity',
    unitPrice: 3100,
    quantity: 0,
    personDays: 0,
    rate: 0,
    rateKey: 'internalLaborTaxRate',
    amountWithTax: 0,
    taxRate: 0,
    sourceNote: '',
    sortOrder: 10,
  },
  {
    id: id('cost'),
    category: 'period_expense',
    name: '管理费用',
    calculationMode: 'revenue_rate',
    unitPrice: 0,
    quantity: 0,
    personDays: 0,
    rate: 0,
    rateKey: 'managementFeeRate',
    amountWithTax: 0,
    taxRate: 0,
    sourceNote: '内部项目地区合同收入6%',
    sortOrder: 11,
  },
  {
    id: id('cost'),
    category: 'period_expense',
    name: '销售费用',
    calculationMode: 'revenue_rate',
    unitPrice: 0,
    quantity: 0,
    personDays: 0,
    rate: 0,
    rateKey: 'salesFeeRate',
    amountWithTax: 0,
    taxRate: 0,
    sourceNote: '',
    sortOrder: 12,
  },
  {
    id: id('cost'),
    category: 'period_expense',
    name: '财务费用',
    calculationMode: 'manual',
    unitPrice: 0,
    quantity: 0,
    personDays: 0,
    rate: 0,
    amountWithTax: 760,
    taxRate: 0,
    sourceNote: '',
    sortOrder: 13,
  },
  {
    id: id('cost'),
    category: 'simulated_interest',
    name: '模拟计息财务费用',
    calculationMode: 'manual',
    unitPrice: 0,
    quantity: 0,
    personDays: 0,
    rate: 0,
    amountWithTax: 0,
    taxRate: 0,
    sourceNote: '',
    sortOrder: 14,
  },
  {
    id: id('cost'),
    category: 'surcharge_tax',
    name: '附加税金',
    calculationMode: 'formula',
    unitPrice: 0,
    quantity: 0,
    personDays: 0,
    rate: 0,
    amountWithTax: 0,
    taxRate: 0,
    sourceNote: '按参数自动计算',
    sortOrder: 15,
  },
];

export const createScenario = (name = 'BIM建模服务费用测算'): Scenario => {
  const timestamp = now();
  return {
    schemaVersion: 1,
    id: id('scenario'),
    name,
    status: 'draft',
    projectInfo: {
      projectName: name,
      customerName: '',
      serviceType: 'BIM建模',
      owner: '',
      estimateDate: today(),
      description: '',
    },
    parameters: { ...defaultParameters },
    revenues: sampleRevenues(),
    costs: sampleCosts(),
    notes: '',
    createdAt: timestamp,
    updatedAt: timestamp,
  };
};

export const cloneScenario = (scenario: Scenario): Scenario => {
  const timestamp = now();
  return {
    ...structuredClone(scenario),
    id: id('scenario'),
    name: `${scenario.name} - 副本`,
    projectInfo: {
      ...scenario.projectInfo,
      projectName: `${scenario.projectInfo.projectName} - 副本`,
    },
    status: 'draft',
    createdAt: timestamp,
    updatedAt: timestamp,
  };
};
